### ISSUE TITLE
Use of composer for installation

### ISSUE THREAD

**Issue by gregrobson** [laravel/nova-docs#42]
I noticed that both times in the documentation you are asked to run `composer update`.

Without specifying a package this will cause all packages within `composer.json` to update to the latest available versions - generally this should work, but you might not want to force an update of all packages depending on workflow or who else is using the repository?

`composer install laravel/nova` might be preferable for first installation.
`composer update laravel/nova` would be preferable for updates.

Composer will of course advise you when dependency versions are too low.

Just a consideration that came to mind.

**Comment by alexfinnarn** [comment]
I guess I'll tag onto this issue since it relates to Composer installing the project.

On https://nova.laravel.com/docs/1.0/installation.html, there is no mention of anything outside of the `nova` subdirectory other than the requirements list and that there is a Laravel application somewhere else. So, for a new person not in the know, I don't see how they could install this project. They might say "What composer.json file do I update?" I assume I need to install the main Laravel project, and a link to those instructions would be nice.
