### ISSUE TITLE
Add section to explain how template customization works 

### ISSUE THREAD

**Issue by dayrontbs12001** [laravel/nova-docs#74]
I think it will be useful add a section in the docs to explain how the template engine works. Today I was wondering how I can make some changes on pages components without modifying the originals Nova view files and can't figure out how. 

Fortunately, A user from StackOverflow helped me -> https://stackoverflow.com/questions/52370915/laravel-nova-template-customization 
but I think it's something must be included in the docs.

**Comment by davidhemphill** [comment]
It's not clear what you're asking here. Are you wanting to customize Nova's Vue components or the layout file that is published when you install?

**Comment by dayrontbs12001** [comment]
Layout files.

**Comment by davidhemphill** [comment]
It's not recommended to modify the layout files published by Nova, so I don't think we're going to document it.

**Comment by davidmpaz** [comment]
I think this is a good point and deserves care in docs. Maybe it was not clearly explained and/or some more infos are needed?

As for me, my particular case is that I want to display a language selector (vue component) in nova.
Questions arose:

1. How to add it to the side bar?
2. How to add it to the header?

My current approach for testing purposes is to add it as a `card`, but this is far from desired result.

What would be the proper approach when you want to customize more than a logo in your nova views? 

From my point of view this is a valid use case for anyone using an admin panel.

Thanks in advance for your time,
David

**Comment by davidhemphill** [comment]
Your tool's navigation can show anything inside of its blade view...including Vue components.

**Comment by davidmpaz** [comment]
Hi @davidhemphill , yes agreed. But please lets keep in focus that main issue is not being able to solve my problem but the customization of templates. I will provide here my solution (mostly duplication of what have been said currently) as a way of documenting whats needed to do. Better to have this than nothing. 

It is unfortunate this issue is closed, many newbees (in nova and laravel) like me can benefits from it.

Thanks for taking time to answer.

Cheers,
David

---
The path followed was to create a *Nova Card*, this way the scaffolded code can be used inside your package if not wanting to use the complete generated package by `nova:card` command.

Files/Dirs transfered to own package (basically all of them):
* src/Cards
* src/CardServiceProvider.php
* routes/api.php
* resources
* webpack.mix.js
* package.json

1. Update `composer.json`, `package.json` and `webpack.mix.js` files accordingly. Add deps, scripts, newly `CardServiceProvider` class, update paths  etc..
2. Udate routes, css and js paths in `CardServiceProvider.php` to match new dir structure.
3. Add partial using component to package's `resources` directory. And publish it from `CardServiceProvider`. `resources/views/vendor/nova/partials/language-selector.blade.php`
4. Copy `resources/views/vendor/nova/layout.blade.php` from published nova resources to our own package resources directory. Modify to convinience and  include partial created before.

This approach  solves the problem, offcourse, from now on, some maintanance efforts need to be done every time you update nova; `layout.blade.php` need to be updated every time.

**Comment by aejnsn** [comment]
@davidhemphill Stop trying to handle this so defensively with Nova updates. I believe we're all developers here, most of us understand the ramifications of what we're doing--hence why we're asking for it. Keeping this some big secret, as I have seen in the countless issues regarding this same topic, is leading to my personal dissatisfaction with Nova as a tool.

I have been working in Laravel since 2012. Nova, and its support (or lack thereof), is uncharacteristic of any project @taylorotwell has worked on thus far. I feel buyer's remorse because of the impasse surrounding the topic originally detailed in the many issues like this one--"How does one override a Vue component used in Nova?"
